# Generated by Django 4.0.1 on 2022-05-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrapermissions',
            name='add_course',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrapermissions',
            name='add_instructor_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrapermissions',
            name='add_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrapermissions',
            name='add_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrapermissions',
            name='add_student_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrapermissions',
            name='add_task',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extrapermissions',
            name='delete_instructor_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='extrapermissions',
            name='user_have_perm',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
