# Generated by Django 4.0.4 on 2022-05-01 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quiz_course_name_alter_question_answerd_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='company_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='answerd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 20, 21, 32, 396084)),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 1, 20, 21, 32, 397198)),
        ),
    ]
