# Generated by Django 4.0.1 on 2022-05-15 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_question_answerd_on_alter_reportresult_on_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answerd_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 9, 39, 55, 419354)),
        ),
        migrations.AlterField(
            model_name='reportresult',
            name='on_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 15, 9, 39, 55, 420349)),
        ),
    ]
