# Generated by Django 4.0.1 on 2022-05-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Schedule_name',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
